<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LTILPUN23200595" name="runner.TestNGTestRunner" tests="1" failures="1" timestamp="2021-02-03T18:41:55 IST" time="146.197" errors="0">
  <testcase name="runScenario" time="146.197" classname="runner.TestNGTestRunner">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at stepDefinitions.web.SignIn_TestStepDefinition.user_enters_UserName_and_Password(SignIn_TestStepDefinition.java:66)
at âœ½.User enters UserName and Password(file:SignIn_Test.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runner.TestNGTestRunner -->
