<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LTILPUN23200595" ignored="0" name="Test" tests="8" failures="1" timestamp="2021-01-26T14:28:45 IST" time="158.69" errors="0">
  <testcase name="runScenario" time="36.266" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="8.267" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="1.983" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="1.976" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="5.757" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="4.899" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="5.649" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="93.467" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="cucumber.api.PendingException" message="TODO: implement me">
      <![CDATA[cucumber.api.PendingException: TODO: implement me
at stepDefinitions.mobilesteps.LoginMobileTestStepDefinition.i_am_able_to_launch_appium(LoginMobileTestStepDefinition.java:46)
at âœ½.I am able to launch appium(file:LoginMobileTest.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Test -->
